# Generated by Django 5.2.7 on 2025-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statue',
            name='discovered_at',
        ),
        migrations.RemoveField(
            model_name='statue',
            name='dynasty',
        ),
        migrations.RemoveField(
            model_name='statue',
            name='location_in_museum',
        ),
        migrations.AddField(
            model_name='statue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='statue_images/'),
        ),
        migrations.AddField(
            model_name='statue',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='models_3d/'),
        ),
        migrations.AlterField(
            model_name='statue',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
